"""update database

Revision ID: 235b7a984955
Revises: aa2a551fd585
Create Date: 2020-05-10 16:01:37.051324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235b7a984955'
down_revision = 'aa2a551fd585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'posted')
    # ### end Alembic commands ###
